import type { Metadata } from "next";
import { roboto, notoJP } from "@/lib/fonts";
import { NextIntlClientProvider, hasLocale } from 'next-intl';
import { notFound } from 'next/navigation';
import { setRequestLocale } from "next-intl/server";
import { getMessages } from "next-intl/server";
import { routing } from "@/i18n/routing";
import "@/app/globals.css";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return [{locale: 'ja'}, {locale: 'en'}];
}

export default async function LocaleLayout({ children, params }: {
  children: React.ReactNode;
  params: {locale: string};
}) {
  const {locale} = await params;

  // 無効な言語の場合は404ページを表示
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  // SSG対応
  setRequestLocale(locale);
  // 言語ファイルの読み込み
  const messages = await getMessages();

  const bodyFont = locale === 'ja' ? notoJP.className : roboto.className; // とりあえず英語の本文はRoboto
  console.log(`Locale: ${locale}, Body Font: ${bodyFont}`);

  return (
    <html lang={locale} style={{ colorScheme: 'light' }}>
      <body className={`${bodyFont} bg-white`}>
          <NextIntlClientProvider locale={locale} messages={messages}>
            <Header/>
            <main className="min-h-screen">
              {children}
            </main>
          </NextIntlClientProvider>
      </body>
    </html>
  );
}
